### PR TITLE
refactoring

### PR DESCRIPTION
**Pull request by goloveychuk**
Now I get `Error: ParseError(description: "HPE_OK: success")` 
when sending from js

### CODE REVIEW

**Comment by goloveychuk** [comment]
HttpParser parsing
https://monosnap.com/file/Pf9ZDUt8cnJjxQbUtlpXKld7JIRnoq.png
But second payload - binary webosocket one. Please help to fix

**Comment by paulofaria** [comment]
what's happening?

**Comment by goloveychuk** [comment]
@paulofaria there was error in zewo/http, after fixing it websocket lib is working

**Comment by paulofaria** [comment]
what was the error?

**Comment by goloveychuk** [comment]
errors are fixed, now pls somebody review @paulofaria

**Pull request merged**
