### PR TITLE
fix when index = -1 in Socket.swift

### LINKED ISSUE #5: fatal error: Index out of range
https://github.com/Zewo/WebSocket/blob/master/Sources/Socket.swift#L395

The index here can be -1

Don't know what this code do, but checking for != -1  solves a runtime error
```swift
let ind = frames.endIndex.predecessor()
if ind != -1 {
    frames[ind] = frame
}
```

Also it was impossible to understand where bug was. 
Stack trace from SPM:
```
fatal error: Index out of range
Current stack trace:
[1]    93505 illegal hardware instruction  .build/debug/Broq
```
Xcode showed random line of code each time.  Looks like it's swift debugger error.

### PR DESCRIPTION
**Pull request by goloveychuk**
Once again, I don't know if it's correct, just guessing. 
Maybe Resolves #5

### CODE REVIEW

**Comment by paulofaria** [comment]
I think the check would be safer if it were `ind >= 0 && ind < frames.count`.

**Comment by paulofaria** [comment]
https://github.com/goloveychuk/WebSocket/blob/master/Sources/Socket.swift#L359

this place could use a check as well.

**Comment by goloveychuk** [comment]
done.

**Comment by paulofaria** [comment]
For this contribution and others I invited you to the GitHub organization team as in: 

https://github.com/Zewo/Zewo/blob/master/CONTRIBUTING.md

Welcome! (:

**Comment by goloveychuk** [comment]
Thanks :) Appreciate it. Will try not to break existing code :)

**Comment by paulofaria** [comment]
Yeah we're going to add more and more unit tests from now on and set up a travis, so people can feel more confident when contributing.

**Comment by paulofaria** [comment]
Actually this is a good place to start contributing. I'll create some tags and tasks on the main repo, along with some explanation in the contributing section.

**Pull request merged**
